import { createHash, generateKeyPairSync } from 'node:crypto';
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { schedPolicyBundles } from '@vega/db';
import type { ObjectStore } from '@vega/objectstore';
import {
  buildDiscoveryBundle,
  buildPresetsBundle,
  buildTenantBundle,
  DISCOVERY_RESOURCE,
  PRESETS_RESOURCE,
  publicPem,
  signingKeyFromPem,
  tenantResource,
  tenantVersionResource,
  type BuiltBundle,
  type Policy,
  type SigningKey,
} from '@vega/policy-engine';
import type { Logger } from '@vega/shared';

/**
 * POLICY DISTRIBUTION (docs/module5.md §8.2): the control plane compiles, signs and writes
 * bundles to object storage; OPA (execution side) polls them through one signed discovery
 * bundle. Neither plane calls the other.
 *
 *   on start      the presets bundle (it ships with the platform) and the discovery bundle
 *   on build      tenants/<t>/v<n>.tar.gz — a candidate; nothing loads it yet
 *   on activate   the candidate's bytes → tenants/<t>/bundle.tar.gz (what OPA polls), and the
 *                 discovery bundle rebuilt so a tenant's first activation is picked up
 */

export const BUNDLE_KEY_ID = 'vega';
export const OPA_SERVICE = 'store';

export interface BundleKeyOptions {
  /** Deployed: the PEM from the secret store (`\n` escapes allowed). */
  pem?: string | undefined;
  /** Development: a file, generated on first use (gitignored). */
  path: string;
  production: boolean;
  log: Logger;
  /** Development: where OPA's configuration is written (it embeds the public key). */
  opaConfigPath?: string;
  /** What OPA's configuration points its `store` service at (development). */
  storeUrl?: string;
}

/** OPA's configuration: verify with our key, discover everything else from a signed bundle. */
export function opaConfig(opts: { storeUrl: string; publicKeyPem: string; s3Signing: boolean }): string {
  const indent = (s: string, n: number) => s.trim().split('\n').map((l) => `${' '.repeat(n)}${l}`).join('\n');
  return [
    '# GENERATED by the control plane (services/control/src/policy/publisher.ts) — development only.',
    '# Deployed OPA gets the same shape from the Helm chart, with the key from the secret store.',
    'services:',
    `  ${OPA_SERVICE}:`,
    `    url: ${opts.storeUrl}`,
    ...(opts.s3Signing ? ['    credentials:', '      s3_signing:', '        environment_credentials: {}'] : []),
    'keys:',
    `  ${BUNDLE_KEY_ID}:`,
    '    algorithm: ES256',
    '    key: |',
    indent(opts.publicKeyPem, 6),
    'discovery:',
    `  resource: ${DISCOVERY_RESOURCE}`,
    `  service: ${OPA_SERVICE}`,
    '  decision: discovery/config',
    '  signing:',
    `    keyid: ${BUNDLE_KEY_ID}`,
    '  polling:',
    '    min_delay_seconds: 2',
    '    max_delay_seconds: 5',
    'decision_logs:',
    '  console: false',
    '',
  ].join('\n');
}

export function loadBundleKey(opts: BundleKeyOptions): SigningKey {
  if (opts.pem) return signingKeyFromPem(opts.pem.replace(/\\n/g, '\n'), BUNDLE_KEY_ID);
  if (!existsSync(opts.path)) {
    if (opts.production) throw new Error(`policy bundle signing key not found at ${opts.path} (OPA_BUNDLE_SIGNING_KEY)`);
    const { privateKey } = generateKeyPairSync('ec', { namedCurve: 'P-256', privateKeyEncoding: { type: 'pkcs8', format: 'pem' }, publicKeyEncoding: { type: 'spki', format: 'pem' } });
    mkdirSync(dirname(opts.path), { recursive: true });
    writeFileSync(opts.path, privateKey, { mode: 0o600 });
    opts.log.warn({ path: opts.path }, 'DEV: generated a policy bundle signing key; deployed environments mount one from the secret store');
  }
  const key = signingKeyFromPem(readFileSync(opts.path, 'utf8'), BUNDLE_KEY_ID);
  if (!opts.production) {
    const configPath = opts.opaConfigPath ?? join(dirname(opts.path), 'opa-config.yaml');
    const config = opaConfig({ storeUrl: opts.storeUrl ?? 'http://seaweedfs:8333/vega-policy', publicKeyPem: publicPem(key), s3Signing: true });
    if (!existsSync(configPath) || readFileSync(configPath, 'utf8') !== config) {
      writeFileSync(configPath, config);
      opts.log.warn({ configPath }, 'DEV: wrote the OPA configuration (restart the opa container if it was already running)');
    }
  }
  return key;
}

export class PolicyPublisher {
  constructor(
    private readonly store: ObjectStore,
    readonly key: SigningKey,
    private readonly log: Logger,
    private readonly polling: { min: number; max: number } = { min: 2, max: 5 },
  ) {}

  /** The presets bundle and the discovery bundle: what OPA needs before any tenant activates. */
  async publishBaseline(): Promise<void> {
    await this.store.ensureBucket();
    const presets = buildPresetsBundle(this.key);
    await this.store.put(PRESETS_RESOURCE, presets.tarGz, 'application/gzip');
    await this.publishDiscovery();
    this.log.info({ presets: presets.revision }, 'policy baseline published (presets + discovery)');
  }

  /** A candidate: compiled, signed and stored under its version; not loaded by anything yet. */
  async buildCandidate(tenantId: string, version: number, policies: ReadonlyArray<{ policy: Policy; version: number }>): Promise<BuiltBundle & { rego: string; ref: string }> {
    const built = buildTenantBundle(tenantId, version, policies, this.key);
    const ref = tenantVersionResource(tenantId, version);
    await this.store.put(ref, built.tarGz, 'application/gzip');
    return { ...built, ref };
  }

  /** Makes a stored candidate the one OPA loads. The bytes are copied as signed, never rebuilt. */
  async activate(tenantId: string, ref: string, digest: string): Promise<void> {
    const bytes = await this.store.get(ref);
    if (!bytes) throw new Error(`bundle ${ref} is missing from object storage`);
    const actual = `sha256:${createHash('sha256').update(bytes).digest('hex')}`;
    if (actual !== digest) throw new Error(`bundle ${ref} does not match its recorded digest (${actual} ≠ ${digest}); refusing to activate it`);
    await this.store.put(tenantResource(tenantId), bytes, 'application/gzip');
  }

  /** Every tenant with an active bundle, listed in the signed discovery bundle. */
  async publishDiscovery(extra: string[] = []): Promise<void> {
    const active = await schedPolicyBundles();
    const tenants = [...new Set([...active.map((a) => a.tenantId), ...extra])].map((tenantId) => ({ tenantId }));
    const discovery = buildDiscoveryBundle({ service: OPA_SERVICE, keyId: this.key.keyId, tenants, polling: this.polling, version: Math.floor(Date.now() / 1000) }, this.key);
    await this.store.put(DISCOVERY_RESOURCE, discovery.tarGz, 'application/gzip');
  }
}
