import type { ToolDeclarationRecord } from '@vega/contracts';
import type { ToolRegistry } from '@vega/connector-sdk';

/**
 * tool_declarations is a PROJECTION of the TypeScript declarations (docs/module2.md §4): the
 * code is the source of truth, the table is what SQL-speaking consumers (risk queries, audit
 * receipts, dashboards) read. This renders the projection as an idempotent upsert that the
 * migration runner re-applies on every run. Regenerate with `pnpm tools:generate`; the
 * declaration-sync test fails if the committed file and the registry disagree.
 *
 * Rows are keyed by (connector_kind, tool_id, version). Old versions stay: evidence recorded
 * against v1 must still resolve after v2 ships. `certified_at` is never touched by the generator.
 */

const lit = (s: string) => `'${s.replace(/'/g, "''")}'`;
const arr = (xs: string[]) => (xs.length ? `ARRAY[${xs.map(lit).join(', ')}]::text[]` : `'{}'::text[]`);
const json = (v: unknown) => `${lit(JSON.stringify(v))}::jsonb`;

function row(r: ToolDeclarationRecord): string {
  return `  (${[
    lit(r.connectorKind),
    lit(r.toolId),
    String(r.version),
    lit(r.title),
    lit(r.description),
    arr(r.scopes),
    lit(r.egressClass),
    lit(r.reversibility),
    lit(r.maxTaint),
    lit(r.outputTaint),
    lit(r.idempotency),
    String(r.sensitivityHint),
    String(r.holdSupported),
    lit(r.simulateFidelity),
    r.compensatorRef === null ? 'NULL' : lit(r.compensatorRef),
    arr(r.recipientArgs),
    json(r.argsSchema),
    json(r.effectSchema),
    r.costHint === null ? 'NULL' : json(r.costHint),
  ].join(', ')})`;
}

const COLUMNS = [
  'connector_kind',
  'tool_id',
  'version',
  'title',
  'description',
  'scopes',
  'egress_class',
  'reversibility',
  'max_taint',
  'output_taint',
  'idempotency',
  'sensitivity_hint',
  'hold_supported',
  'simulate_fidelity',
  'compensator_ref',
  'recipient_args',
  'args_schema',
  'effect_schema',
  'cost_hint',
];

export function declarationsSql(registry: ToolRegistry): string {
  const records = registry.records();
  const updates = COLUMNS.slice(3)
    .map((c) => `  ${c} = EXCLUDED.${c}`)
    .join(',\n');
  return [
    '-- GENERATED by `pnpm tools:generate` from the connector registry. DO NOT EDIT.',
    '-- docs/module2.md §4: tool_declarations is a projection of the TypeScript declarations.',
    `-- ${records.length} tool declaration(s).`,
    '',
    `INSERT INTO tool_declarations (${COLUMNS.join(', ')}) VALUES`,
    records.map(row).join(',\n'),
    'ON CONFLICT (connector_kind, tool_id, version) DO UPDATE SET',
    updates + ';',
    '',
  ].join('\n');
}
